import = [
    "~/.config/alacritty/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10

decorations = "Buttonless"

[font]
normal.family = "IntoneMono Nerd Font"

size = 13.5

[shell]
program= "/bin/zsh"
